### ISSUE TITLE
bad if-condition

### ISSUE THREAD

**Issue by mb706** [a-hanf/mlr3automl#12]
https://github.com/a-hanf/mlr3automl/blob/e15722650a1ec9e66b1a66dcf2e37d3ce6bb3041/R/AutoMLBase.R#L191

When `learner_timeout` is not `NULL`, then the condition evaluates to `TRUE`, when `learner_timeout` is `NULL`, then it evaluates to `NA`.

**Comment by a-hanf** [comment]
Thanks for the report, fixed in #14
