### ISSUE TITLE
Should mlr3 be in Depends instead of Imports?

### ISSUE THREAD

**Issue by ledell** [a-hanf/mlr3automl#20]
Currently, all the packages that **mlr3automl** depends on are in the Imports section of the DESCRIPTION file.  I wonder if it would be helpful to move **mlr3** to Depends, so you don't need to explicitly load it when running the examples?

```
> library(mlr3automl)
> iris_task <- tsk('iris')
Error in tsk("iris") : could not find function "tsk"
```

You have to do this:
```
library(mlr3)
library(mlr3automl)

iris_task <- tsk('iris')
model <- AutoML(iris_task)
model$train()
```

**Comment by a-hanf** [comment]
Thanks for the suggestion and sorry for leaving this unanswered for so long.
We discussed this internally and won't be making changes here
